### ISSUE TITLE
it says visual c++  14 required

### ISSUE THREAD

**Issue by hyndex** [renjithsraj/paywix_demos#1]
ERROR: Command errored out with exit status 1: 'c:\users\diki\desktop\sabpad\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\diki\\AppData\\Local\\Temp\\pip-install-o6ix6_a3\\pycrypto\\setup.py'"'"'; __file__='"'"'C:\\Users\\diki\\AppData\\Local\\Temp\\pip-install-o6ix6_a3\\pycrypto\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\diki\AppData\Local\Temp\pip-record-d2h5042z\install-record.txt' --single-version-externally-managed --compile --install-headers

**Comment by renjithsraj** [comment]
I think you were trying to install `paywix` in windows platform, I think may be you are missing python setuptools in the platform or environment,  I have tried with ubuntu/mac os it's working well, so Need to check the issues, if already resolve the issue, please help me.
Thanks

**Comment by hyndex** [comment]
thnx ..

**Comment by hyndex** [comment]
i also appreciate your great work on this ..
